name: tpdne
channels:
  - pytorch
  - nvidia
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - absl-py=2.1.0
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.37
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - grpcio=1.62.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.7
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.37
  - libcurand-dev=10.3.7.37
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.2.2
  - ply=3.11
  - prompt-toolkit=3.0.47
  - protobuf=4.25.3
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - requests=2.32.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - torchinfo=1.8.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torchaudio==2.4.0
      - torcheval==0.0.7
      - torchsummary==1.5.1
      - torchvision==0.19.0
      - tqdm==4.66.5
