name: tpdne
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=24.2
  - python=3.12.4
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=11.8
  - tensorboard=2.17.0
  - pip:
      - torcheval==0.0.7
      - torchinfo==1.8.0
      - tqdm==4.66.5
